baseURL = "https://rankki.xyz/"
languageCode = "zh-cn"
googleAnalytics = "UA-102355473-2"

title = "RanKKI's Blog"
author = "Hugh(Hui) Liu"
copyright = "Hugh(Hui) Liu"

theme = "cactus"
paginate = 15

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

[markup.goldmark.renderer]
  unsafe= true

[params]
  showCategories = false
  colortheme = "white"

[taxonomies]
  tag = "tags"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 2

[[menu.main]]
  name = "Tags"
  url = "/tags"
  weight = 3