baseURL = "https://rankki.xyz/"
languageCode = "zh-cn"
googleAnalytics = "UA-102355473-2"

title = "RanKKI's Blog"
author = "Hugh(Hui) Liu"
copyright = "Hugh(Hui) Liu"

enableGitInfo = true

pygmentsCodeFences = true
pygmentsUseClasses = true

theme = "cactus"
paginate = 15

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "tango"
    tabWidth = 4

[markup.goldmark.renderer]
  unsafe= true

[params]
  showCategories = true
  colortheme = "white"
  css = ["syntax.css"]
  postsonhomepage = 15
  disablecopy = false
  showReadTime = true
  show_updated = true
  mainSections = ['posts']
  showProjectsList = true

[taxonomies]
  tag = "tags"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 2

[[menu.main]]
  name = "Tags"
  url = "/tags"
  weight = 3

