baseURL = "https://rankki.xyz/"
languageCode = "zh-cn"
title = "RanKKI's Blog"
author = "Hugh(Hui) Liu"
copyright = "Hugh(Hui) Liu"

theme = "cactus"
paginate = 15

[markup.goldmark.renderer]
unsafe= true

[params]
  showAllPostsOnHomePage = true
  showCategories = true
  rss = true

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3